arb-dir: lib/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: intl_untranslated_messages.json
nullable-getters: false
preferred-supported-locales:
  - en
  - ja